# Generated by Django 3.1.5 on 2021-01-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('gallery_image', models.ImageField(default='p1.jpg', null=True, upload_to='gallery')),
            ],
        ),
    ]
