# Generated by Django 3.0.3 on 2021-07-01 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_tsriffchart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TsriffChart',
            new_name='TariffChart',
        ),
    ]
