# Generated by Django 3.1.5 on 2021-01-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210120_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='gallery_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
