# Generated by Django 3.0.3 on 2021-07-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210701_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffchart',
            name='tariff_per_hr',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
