# Generated by Django 3.0.3 on 2021-07-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_tariffchart_tariff_per_hr'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='checking',
            field=models.TextField(blank=True),
        ),
    ]
