# Generated by Django 3.1.5 on 2021-01-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('designation', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('facebooklink', models.CharField(max_length=300)),
                ('instalink', models.CharField(max_length=300)),
                ('twiterlink', models.CharField(max_length=300)),
                ('linkdnlink', models.CharField(max_length=300)),
            ],
        ),
    ]
