# Generated by Django 3.0.3 on 2021-07-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_news_checking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='checking',
            new_name='news_desc',
        ),
        migrations.AddField(
            model_name='serviceproduct',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
