# Generated by Django 3.0.3 on 2021-07-05 08:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210705_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproduct',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
