# Generated by Django 3.0.3 on 2021-07-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210705_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceproduct',
            name='productdescription',
        ),
        migrations.AlterField(
            model_name='ceategory',
            name='category',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='ceategory',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='defination',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='serviceproduct',
            name='productname',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='facebooklink',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='instalink',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='linkdnlink',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='twiterlink',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='designation',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='quotes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
