# Generated by Django 3.1.5 on 2021-01-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210122_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serviceategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=225)),
            ],
        ),
    ]
