# Generated by Django 3.1.5 on 2021-01-22 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_serviceproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ceategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=225)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.AlterField(
            model_name='serviceproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ceategory'),
        ),
        migrations.DeleteModel(
            name='Serviceategory',
        ),
    ]
